jobs:
  test:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./check/ci

name: Ci

on:
  schedule:
    - cron: "25 */6 * * *"
